setwd("C:/Users/Haonan/Desktop/Study/R/exploratory project")
files <- file('./household_power_consumption.txt')
subsetted <- read.table(text = grep("^[1,2]/2/2007",readLines(files),value=TRUE), sep = ';', col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), na.strings = '?')

#Plot4
png("Plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
plot(datetime, subsetted$Global_active_power, xlab = " ", ylab = "Global Active Power", type = "l")
plot(datetime,subsetted$Voltage, ylab = "Voltage", type = "l")
plot(datetime, subsetted$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
lines(datetime,subsetted$Sub_metering_1, type = "l",  col = "black")
lines(datetime,subsetted$Sub_metering_2, type = "l",  col = "red")
lines(datetime,subsetted$Sub_metering_3, type = "l",  col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"), lty = 1, bty = "n", cex = 0.4)
plot(datetime, subsetted$Global_reactive_power, ylab = "Global_reactive_power", type = "l")
dev.off()
